// src/panels/header/header.tsx
import "./header.css";

interface HeaderProps {
  money: number;
}

export const Header = ({ money }: HeaderProps) => (
  <>
    <a href="https://github.com/ingenmaffen/dev-clicker" className="source">
      https://github.com/ingenmaffen/dev-clicker
    </a>
    <h1 className="title">
      <img className="logo" src={"logo512.png"} alt={"logo"} />
      <span>Dev Clicker</span>
    </h1>
    <div className="info-container">
      <div className="placeholder"></div>
      <div className="money-container">$ {money}</div>
    </div>
  </>
);

// src/app/components/header/header.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "dc-header",
    templateUrl: "./header.component.html",
    styleUrls: ["./header.component.scss"],
})
export class HeaderComponent {
    public money: number = 0;
}

<a href="https://github.com/ingenmaffen/dev-clicker" class="source">
    https://github.com/ingenmaffen/dev-clicker
</a>
<h1 class="title">
    <img class="logo" src="assets/logo512.png" alt="logo" />
    <span>Dev Clicker</span>
</h1>
<div class="info-container">
    <div class="placeholder"></div>
    <div class="money-container">$ {{ money }}</div>
</div>
