// src/Layout/ResourcePanel.jsx
import './ResourcePanel.css';
import { HirePersonButton } from "../Common/HirePersonButton";

const humanResources = [
    {
        text: "Hire a developer"
    },
    {
        text: "Hire a Tester"
    },
    {
        text: "Hire a Business Analyst"
    },
    {
        text: "Hire a Product Owner"
    }
];


export const ResourcePanel = () => (
    <div className="human-resources-panel">
        {humanResources.map(person => <HirePersonButton key={person.text} {...person} />)}
    </div>
);

// src/app/components/resource-panel/resource-panel.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "dc-resource-panel",
    templateUrl: "./resource-panel.component.html",
    styleUrls: ["./resource-panel.component.scss"],
})
export class ResourcePanelComponent {
    public humanResources = [
        {
            type: "developer",
            displayText: "Developer",
            icon: "assets/coding.png",
        },
        {
            type: "tester",
            displayText: "Tester",
            icon: "assets/bug.png",
        },
        {
            type: "businessAnalyst",
            displayText: "Business Analyst",
            icon: "assets/analytics.png",
        },
        {
            type: "productOwner",
            displayText: "Product Owner",
            icon: "assets/user.png",
        },
    ];

    public hire(resourceType: string): void {}
}

<div class="human-resources-panel">
    <button *ngFor="let resource of humanResources" (click)="hire(resource.type)" class="common-button">
        <div class="left-side">
            <img [src]="resource.icon" [alt]="resource.displayText" />
            <span>{{ resource.displayText }}</span>
        </div>
        <div class="right-side">0</div>
    </button>
</div>
